// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.4.0
// - protoc             v3.12.4
// source: proto/blockchain.proto

package blockchain

import (
	context "context"
	empty "github.com/golang/protobuf/ptypes/empty"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.62.0 or later.
const _ = grpc.SupportPackageIsVersion8

const (
	Node_HandleHandshake_FullMethodName      = "/Node/HandleHandshake"
	Node_HandleTransaction_FullMethodName    = "/Node/HandleTransaction"
	Node_HandleBlock_FullMethodName          = "/Node/HandleBlock"
	Node_HandlePreVote_FullMethodName        = "/Node/HandlePreVote"
	Node_HandlePreCommit_FullMethodName      = "/Node/HandlePreCommit"
	Node_DumpPeers_FullMethodName            = "/Node/DumpPeers"
	Node_DumpBlockStore_FullMethodName       = "/Node/DumpBlockStore"
	Node_DumpBlockList_FullMethodName        = "/Node/DumpBlockList"
	Node_DumpTransactionStore_FullMethodName = "/Node/DumpTransactionStore"
	Node_DumpUTXOSet_FullMethodName          = "/Node/DumpUTXOSet"
)

// NodeClient is the client API for Node service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type NodeClient interface {
	HandleHandshake(ctx context.Context, in *Handshake, opts ...grpc.CallOption) (*Handshake, error)
	HandleTransaction(ctx context.Context, in *Transaction, opts ...grpc.CallOption) (*Ack, error)
	HandleBlock(ctx context.Context, in *Block, opts ...grpc.CallOption) (*Ack, error)
	HandlePreVote(ctx context.Context, in *PreVote, opts ...grpc.CallOption) (*Ack, error)
	HandlePreCommit(ctx context.Context, in *PreCommit, opts ...grpc.CallOption) (*Ack, error)
	DumpPeers(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*StringDump, error)
	DumpBlockStore(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*BytesDump, error)
	DumpBlockList(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*BytesDump, error)
	DumpTransactionStore(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*BytesDump, error)
	DumpUTXOSet(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*BytesDump, error)
}

type nodeClient struct {
	cc grpc.ClientConnInterface
}

func NewNodeClient(cc grpc.ClientConnInterface) NodeClient {
	return &nodeClient{cc}
}

func (c *nodeClient) HandleHandshake(ctx context.Context, in *Handshake, opts ...grpc.CallOption) (*Handshake, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Handshake)
	err := c.cc.Invoke(ctx, Node_HandleHandshake_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeClient) HandleTransaction(ctx context.Context, in *Transaction, opts ...grpc.CallOption) (*Ack, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Ack)
	err := c.cc.Invoke(ctx, Node_HandleTransaction_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeClient) HandleBlock(ctx context.Context, in *Block, opts ...grpc.CallOption) (*Ack, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Ack)
	err := c.cc.Invoke(ctx, Node_HandleBlock_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeClient) HandlePreVote(ctx context.Context, in *PreVote, opts ...grpc.CallOption) (*Ack, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Ack)
	err := c.cc.Invoke(ctx, Node_HandlePreVote_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeClient) HandlePreCommit(ctx context.Context, in *PreCommit, opts ...grpc.CallOption) (*Ack, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Ack)
	err := c.cc.Invoke(ctx, Node_HandlePreCommit_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeClient) DumpPeers(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*StringDump, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StringDump)
	err := c.cc.Invoke(ctx, Node_DumpPeers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeClient) DumpBlockStore(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*BytesDump, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BytesDump)
	err := c.cc.Invoke(ctx, Node_DumpBlockStore_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeClient) DumpBlockList(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*BytesDump, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BytesDump)
	err := c.cc.Invoke(ctx, Node_DumpBlockList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeClient) DumpTransactionStore(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*BytesDump, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BytesDump)
	err := c.cc.Invoke(ctx, Node_DumpTransactionStore_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeClient) DumpUTXOSet(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*BytesDump, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BytesDump)
	err := c.cc.Invoke(ctx, Node_DumpUTXOSet_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NodeServer is the server API for Node service.
// All implementations must embed UnimplementedNodeServer
// for forward compatibility
type NodeServer interface {
	HandleHandshake(context.Context, *Handshake) (*Handshake, error)
	HandleTransaction(context.Context, *Transaction) (*Ack, error)
	HandleBlock(context.Context, *Block) (*Ack, error)
	HandlePreVote(context.Context, *PreVote) (*Ack, error)
	HandlePreCommit(context.Context, *PreCommit) (*Ack, error)
	DumpPeers(context.Context, *empty.Empty) (*StringDump, error)
	DumpBlockStore(context.Context, *empty.Empty) (*BytesDump, error)
	DumpBlockList(context.Context, *empty.Empty) (*BytesDump, error)
	DumpTransactionStore(context.Context, *empty.Empty) (*BytesDump, error)
	DumpUTXOSet(context.Context, *empty.Empty) (*BytesDump, error)
	mustEmbedUnimplementedNodeServer()
}

// UnimplementedNodeServer must be embedded to have forward compatible implementations.
type UnimplementedNodeServer struct {
}

func (UnimplementedNodeServer) HandleHandshake(context.Context, *Handshake) (*Handshake, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HandleHandshake not implemented")
}
func (UnimplementedNodeServer) HandleTransaction(context.Context, *Transaction) (*Ack, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HandleTransaction not implemented")
}
func (UnimplementedNodeServer) HandleBlock(context.Context, *Block) (*Ack, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HandleBlock not implemented")
}
func (UnimplementedNodeServer) HandlePreVote(context.Context, *PreVote) (*Ack, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HandlePreVote not implemented")
}
func (UnimplementedNodeServer) HandlePreCommit(context.Context, *PreCommit) (*Ack, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HandlePreCommit not implemented")
}
func (UnimplementedNodeServer) DumpPeers(context.Context, *empty.Empty) (*StringDump, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DumpPeers not implemented")
}
func (UnimplementedNodeServer) DumpBlockStore(context.Context, *empty.Empty) (*BytesDump, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DumpBlockStore not implemented")
}
func (UnimplementedNodeServer) DumpBlockList(context.Context, *empty.Empty) (*BytesDump, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DumpBlockList not implemented")
}
func (UnimplementedNodeServer) DumpTransactionStore(context.Context, *empty.Empty) (*BytesDump, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DumpTransactionStore not implemented")
}
func (UnimplementedNodeServer) DumpUTXOSet(context.Context, *empty.Empty) (*BytesDump, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DumpUTXOSet not implemented")
}
func (UnimplementedNodeServer) mustEmbedUnimplementedNodeServer() {}

// UnsafeNodeServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NodeServer will
// result in compilation errors.
type UnsafeNodeServer interface {
	mustEmbedUnimplementedNodeServer()
}

func RegisterNodeServer(s grpc.ServiceRegistrar, srv NodeServer) {
	s.RegisterService(&Node_ServiceDesc, srv)
}

func _Node_HandleHandshake_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Handshake)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServer).HandleHandshake(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Node_HandleHandshake_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServer).HandleHandshake(ctx, req.(*Handshake))
	}
	return interceptor(ctx, in, info, handler)
}

func _Node_HandleTransaction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Transaction)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServer).HandleTransaction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Node_HandleTransaction_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServer).HandleTransaction(ctx, req.(*Transaction))
	}
	return interceptor(ctx, in, info, handler)
}

func _Node_HandleBlock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Block)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServer).HandleBlock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Node_HandleBlock_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServer).HandleBlock(ctx, req.(*Block))
	}
	return interceptor(ctx, in, info, handler)
}

func _Node_HandlePreVote_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PreVote)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServer).HandlePreVote(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Node_HandlePreVote_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServer).HandlePreVote(ctx, req.(*PreVote))
	}
	return interceptor(ctx, in, info, handler)
}

func _Node_HandlePreCommit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PreCommit)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServer).HandlePreCommit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Node_HandlePreCommit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServer).HandlePreCommit(ctx, req.(*PreCommit))
	}
	return interceptor(ctx, in, info, handler)
}

func _Node_DumpPeers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServer).DumpPeers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Node_DumpPeers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServer).DumpPeers(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Node_DumpBlockStore_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServer).DumpBlockStore(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Node_DumpBlockStore_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServer).DumpBlockStore(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Node_DumpBlockList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServer).DumpBlockList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Node_DumpBlockList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServer).DumpBlockList(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Node_DumpTransactionStore_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServer).DumpTransactionStore(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Node_DumpTransactionStore_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServer).DumpTransactionStore(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Node_DumpUTXOSet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServer).DumpUTXOSet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Node_DumpUTXOSet_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServer).DumpUTXOSet(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// Node_ServiceDesc is the grpc.ServiceDesc for Node service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Node_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "Node",
	HandlerType: (*NodeServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "HandleHandshake",
			Handler:    _Node_HandleHandshake_Handler,
		},
		{
			MethodName: "HandleTransaction",
			Handler:    _Node_HandleTransaction_Handler,
		},
		{
			MethodName: "HandleBlock",
			Handler:    _Node_HandleBlock_Handler,
		},
		{
			MethodName: "HandlePreVote",
			Handler:    _Node_HandlePreVote_Handler,
		},
		{
			MethodName: "HandlePreCommit",
			Handler:    _Node_HandlePreCommit_Handler,
		},
		{
			MethodName: "DumpPeers",
			Handler:    _Node_DumpPeers_Handler,
		},
		{
			MethodName: "DumpBlockStore",
			Handler:    _Node_DumpBlockStore_Handler,
		},
		{
			MethodName: "DumpBlockList",
			Handler:    _Node_DumpBlockList_Handler,
		},
		{
			MethodName: "DumpTransactionStore",
			Handler:    _Node_DumpTransactionStore_Handler,
		},
		{
			MethodName: "DumpUTXOSet",
			Handler:    _Node_DumpUTXOSet_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/blockchain.proto",
}
